"""empty message

Revision ID: 75bab603c118
Revises: 
Create Date: 2017-09-12 14:53:26.938000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bab603c118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(u'items_list_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'shopping_list', ['list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'shopping_list_user_id_fkey', 'shopping_list', type_='foreignkey')
    op.create_foreign_key(None, 'shopping_list', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_list', type_='foreignkey')
    op.create_foreign_key(u'shopping_list_user_id_fkey', 'shopping_list', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(u'items_list_id_fkey', 'items', 'shopping_list', ['list_id'], ['id'])
    op.alter_column('items', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
