"""empty message

Revision ID: 9f8097b765fc
Revises: 
Create Date: 2018-01-17 10:16:25.423154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8097b765fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.String(length=32), nullable=True))
    op.drop_column('items', 'item_name')
    op.add_column('shopping_list', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_constraint('shopping_list_list_name_key', 'shopping_list', type_='unique')
    op.create_unique_constraint(None, 'shopping_list', ['name'])
    op.drop_column('shopping_list', 'list_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('list_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shopping_list', type_='unique')
    op.create_unique_constraint('shopping_list_list_name_key', 'shopping_list', ['list_name'])
    op.drop_column('shopping_list', 'name')
    op.add_column('items', sa.Column('item_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('items', 'name')
    # ### end Alembic commands ###
